### ISSUE TITLE
segfault under heavy usage

### ISSUE THREAD

**Issue by datacompboy** [tex/fusecompress#11]
Hello!
[575211.244134] fusecompress[17389]: segfault at 10 ip 00007f89f66ee00f sp 00007f89a17f9a80 error 4 in libpthread-2.18.so[7f89f66e2000+18000]
Anyone else catch that fun?
kernel 3.13.6, libc6 2.18-4, latest fusecompress.

**Comment by danielsokolowski** [comment]
I believe I am getting that too but on an older version, however I can't confirm, do you also get ' Transport endpoint is not connected' errors ?

**Comment by danielsokolowski** [comment]
![fusecompress-transport-endpoint-is-not-connected](https://cloud.githubusercontent.com/assets/273413/12979616/455c95b0-d0a6-11e5-87eb-234c25568584.png)

**Comment by datacompboy** [comment]
Closing since we no longer use it anymore .
