### ISSUE TITLE
lz4 compression

### ISSUE THREAD

**Issue by reflectivedevelopment** [tex/fusecompress#24]
It appears at some point I added lz4 compression at https://github.com/reflectivedevelopment/fusecompress

If you are interested in testing it out and merging it in.

**Comment by tex** [comment]
Feel free to create a merge request, I'll merge it. But since I do not use it anymore I will depend on you to do the testing.

**Comment by reflectivedevelopment** [comment]
I won't have time to test it, so I'll simply close the issue. If others have interest they can pick up the issue.
