### ISSUE TITLE
 Could not link against boost_serialization ! on Ubuntu 11.04

### ISSUE THREAD

**Issue by ubuntupunk** [tex/fusecompress#5]
configure: WARNING: BOOST_CPPFLAGS -I/usr/include
checking whether the Boost::Serialization library is available... yes
checking for exit in -lboost_serialization... no
configure: error: Could not link against boost_serialization !

**Comment by JuliB15** [comment]
Use --with-boost-libdir=/your/path/to/lib
Check where your boost libraries are layed down. Maybe in stage, or in another lib directory. This is a known issue with a known solution.
